[package]
name = "wamn-postgres-sqlx"
version.workspace = true
edition.workspace = true
description = "SQLx driver for the wamn:postgres capability"
license = "Apache-2.0"

[dependencies]
futures-core = "0.3"
futures-util = "0.3"
log = "0.4"
sqlx-core.workspace = true
wit-bindgen.workspace = true

[dev-dependencies]
futures-executor = "0.3"
sqlx = { version = "=0.9.0", default-features = false }

[lints]
workspace = true
