[package]
name = "wamn-client-acme-receiving-tests"
description = "Acme Receiving application integration tests"
workspace = "../../.."
version.workspace = true
edition.workspace = true
license.workspace = true
autotests = false

[lib]
path = "lib.rs"

[dev-dependencies]
serde_json = { workspace = true }
wamn-catalog = { workspace = true }
wamn-control = { workspace = true }
wamn-execution-contract = { workspace = true }
wamn-schema-generator = { workspace = true }

[lints]
workspace = true
