[package]
name = "http-route"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
wit-bindgen = { workspace = true, features = ["async", "async-spawn"] }
wamn-execution-contract = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
futures = "0.3"
