[package]
name = "http-route"
version.workspace = true
edition.workspace = true

[dependencies]
boon = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
wit-bindgen = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true
