[package]
name = "receiving"
version.workspace = true
edition.workspace = true
description = "Package-grain Receiving operation component"
license = "Apache-2.0"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
uuid.workspace = true
wamn-receiving-data-access = { workspace = true }
wamn-postgres-statements = { workspace = true }
wit-bindgen = { workspace = true, features = ["async-spawn"] }

[lib]
crate-type = ["cdylib"]
bench = false

[lints]
workspace = true
