[package]
name = "wamn-host"
description = "General wasmCloud washlet host service."
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
wamn-execution-host = { workspace = true }
wamn-runtime = { workspace = true }
wash-runtime = { workspace = true, features = ["washlet", "wasi-config", "wasi-otel"] }
anyhow = { workspace = true }
async-nats = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal"] }
tracing = { workspace = true }
