apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: wamn-edge
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if .Values.gcp.project }}
  annotations:
    cloud.google.com/neg: {{ printf "{\"exposed_ports\":{\"443\":{\"name\":\"%s\"}}}" .Release.Name | quote }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: wamn-edge
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: https
      port: 443
      targetPort: https
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
