[package]
name = "wamn-dm1"
version.workspace = true
edition.workspace = true

[dependencies]
wamn-schema-compiler = { workspace = true }
wamn-schema-model = { workspace = true }
wamn-schema-control = { workspace = true }

[dev-dependencies]
wamn-project-state = { workspace = true }
serde_json = { workspace = true }
