[package]
name = "wamn-test-postgres"
description = "Private PostgreSQL 18 servers and databases for tests."
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "lib.rs"

[dependencies]
anyhow = { workspace = true }
hex = { workspace = true }
url = { workspace = true }

[lints]
workspace = true
