//! 5.5f — render the custom node's runtime DEPLOYMENT manifest, grants DERIVED
//! from its WIT imports (design-note 7).
//!
//! PLAN-vs-SHIPPED FORK (recorded for the reader): the platform plan describes a
//! `WorkloadDeployment` (the operator OCI-fetches the artifact). That fork is
//! UNSHIPPED — OCI-fetch is wamn-fqg.21's open scope — so v0 emits the SHIPPED
//! `serve-node` Deployment shape (`deploy/platform/serve-node.yaml`): a ConfigMap-
//! mounted node, `wamn-host serve-node`, the `--allowed-hosts` arg, `WAMN_PROJECT`
//! + the credential vault (which holds the runner→node signing key). The emitted
//! YAML carries the OCI ref + digest + signature as metadata ANNOTATIONS so
//! fqg.21's future operator can adopt it.
//!
//! The one derived grant that surfaces as a runtime ARG is `--allowed-hosts`:
//! present iff the node imports `wasi:http/outgoing-handler`, REFUSED otherwise
//! ([`wamn_host::egress_guard::check_allowed_hosts_grant`]) — grants derived from
//! imports, never declared twice.

use anyhow::Context as _;
use wamn_host::egress_guard::{DerivedGrants, check_allowed_hosts_grant};

/// The inputs to a serve-node deployment render (everything not derived from the
/// component's imports).
pub struct EmitInputs {
    /// The node-type slug (names the Deployment / Service / labels).
    pub node_type: String,
    /// The pushed OCI reference (`registry/repo:tag`), an annotation for fqg.21.
    pub image: String,
    /// The signed digest (`sha256:<hex>`), an annotation for fqg.21.
    pub signed_digest: String,
    /// The hex ed25519 signature, an annotation for fqg.21 (`None` = unsigned).
    pub signature: Option<String>,
    /// The project whose vault credentials the node may read (`WAMN_PROJECT`).
    pub project: String,
    /// The hosts the node's outbound `wasi:http` may reach (from `--allowed-host`).
    /// REQUIRED iff the node imports `wasi:http`, REFUSED otherwise.
    pub allowed_hosts: Vec<String>,
}

/// Render the serve-node Deployment + Service YAML for a node whose imports
/// derive `grants`. Refuses (via [`check_allowed_hosts_grant`]) if the declared
/// allowed-hosts do not match the derived grant: an http node needs a non-empty
/// list, a non-http node must not declare one.
pub fn render_serve_node_deployment(
    inputs: &EmitInputs,
    grants: &DerivedGrants,
) -> anyhow::Result<String> {
    check_allowed_hosts_grant(grants, &inputs.allowed_hosts, &inputs.node_type)
        .map_err(|e| anyhow::anyhow!("{e}"))?;

    let name = format!("serve-node-{}", inputs.node_type);
    let mut out = String::new();

    out.push_str(&format!(
        "# Generated by wamn-builder (5.5f). The serve-node runtime manifest for a\n\
         # custom node; grants DERIVED from its WIT imports (design-note 7). The plan's\n\
         # WorkloadDeployment (OCI fetch) is wamn-fqg.21; v0 ships the serve-node\n\
         # Deployment shape (deploy/platform/serve-node.yaml).\n\
         apiVersion: apps/v1\n\
         kind: Deployment\n\
         metadata:\n\
         \x20 name: {name}\n\
         \x20 namespace: wamn-system\n\
         \x20 labels: {{ app: {name} }}\n\
         \x20 annotations:\n\
         \x20\x20\x20 wamn.node.oci-ref: {:?}\n\
         \x20\x20\x20 wamn.node.signed-digest: {:?}\n",
        inputs.image, inputs.signed_digest,
    ));
    if let Some(sig) = &inputs.signature {
        out.push_str(&format!("    wamn.node.signature: {sig:?}\n"));
    }
    out.push_str(&format!(
        "spec:\n\
         \x20 replicas: 1\n\
         \x20 selector: {{ matchLabels: {{ app: {name} }} }}\n\
         \x20 template:\n\
         \x20\x20\x20 metadata:\n\
         \x20\x20\x20\x20\x20 labels: {{ app: {name} }}\n\
         \x20\x20\x20 spec:\n\
         \x20\x20\x20\x20\x20 automountServiceAccountToken: false\n\
         \x20\x20\x20\x20\x20 containers:\n\
         \x20\x20\x20\x20\x20\x20\x20 - name: serve-node\n\
         \x20\x20\x20\x20\x20\x20\x20\x20\x20 image: wamn-host:dev\n\
         \x20\x20\x20\x20\x20\x20\x20\x20\x20 imagePullPolicy: IfNotPresent\n\
         \x20\x20\x20\x20\x20\x20\x20\x20\x20 args:\n\
         \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20 - \"--log-level\"\n\
         \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20 - \"info\"\n\
         \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20 - \"serve-node\"\n\
         \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20 - \"--node\"\n\
         \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20 - \"/components/node.wasm\"\n\
         \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20 - \"--port\"\n\
         \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20 - \"8080\"\n",
    ));
    // The derived --allowed-hosts grant: present iff wasi:http is imported.
    if grants.requires_allowed_hosts {
        out.push_str("            - \"--allowed-hosts\"\n");
        out.push_str(&format!(
            "            - {:?}\n",
            inputs.allowed_hosts.join(",")
        ));
    }
    out.push_str(&format!(
        "\x20\x20\x20\x20\x20\x20\x20\x20\x20 env:\n\
         \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20 - name: WAMN_PROJECT\n\
         \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20 value: {:?}\n\
         \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20 - name: WAMN_CREDENTIALS_FILE\n\
         \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20 value: /etc/wamn/credentials/credentials.json\n\
         \x20\x20\x20\x20\x20\x20\x20\x20\x20 ports:\n\
         \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20 - containerPort: 8080\n\
         \x20\x20\x20\x20\x20\x20\x20\x20\x20 resources:\n\
         \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20 requests: {{ cpu: \"100m\", memory: \"128Mi\" }}\n\
         \x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20 limits: {{ memory: \"384Mi\" }}\n\
         ---\n\
         apiVersion: v1\n\
         kind: Service\n\
         metadata:\n\
         \x20 name: {name}\n\
         \x20 namespace: wamn-system\n\
         spec:\n\
         \x20 selector: {{ app: {name} }}\n\
         \x20 ports:\n\
         \x20\x20\x20 - port: 8080\n\
         \x20\x20\x20\x20\x20 targetPort: 8080\n",
        inputs.project,
    ));
    Ok(out)
}

/// Render + write the deployment manifest to `path`.
pub async fn write_deployment(
    path: &std::path::Path,
    inputs: &EmitInputs,
    grants: &DerivedGrants,
) -> anyhow::Result<()> {
    let yaml = render_serve_node_deployment(inputs, grants)?;
    tokio::fs::write(path, yaml)
        .await
        .with_context(|| format!("write deployment manifest {}", path.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use wamn_host::egress_guard::derive_grants;

    #[test]
    fn http_node_requires_allowed_hosts() {
        let grants = derive_grants(["wasi:http/outgoing-handler@0.2.6"]);
        let inputs = EmitInputs {
            node_type: "http-node".to_string(),
            image: "reg/x:dev".to_string(),
            signed_digest: "sha256:00".to_string(),
            signature: None,
            project: "default".to_string(),
            allowed_hosts: vec![], // empty -> refused for an http node
        };
        assert!(render_serve_node_deployment(&inputs, &grants).is_err());
    }

    #[test]
    fn world_node_refuses_spurious_allowed_hosts() {
        let grants = derive_grants(std::iter::empty::<&str>());
        let inputs = EmitInputs {
            node_type: "world-node".to_string(),
            image: "reg/x:dev".to_string(),
            signed_digest: "sha256:00".to_string(),
            signature: None,
            project: "default".to_string(),
            allowed_hosts: vec!["api.example:443".to_string()], // spurious -> refused
        };
        assert!(render_serve_node_deployment(&inputs, &grants).is_err());
    }
}
