[package]
name = "wms"
version.workspace = true
edition.workspace = true
description = "Package-grain WMS operation component"
license = "Apache-2.0"

[dependencies]
futures-executor = "0.3"
wamn-wms-data-access = { workspace = true }
wit-bindgen = { workspace = true }

[lib]
crate-type = ["cdylib"]
test = false
bench = false

[lints]
workspace = true
