-- `new_pallet_id` is pre-generated by the claim, exactly as `movement_id` is.
-- A split that minted its pallet id during the work would mint a SECOND pallet
-- on replay, which is the duplicate the idempotency key exists to prevent —
-- and the one that would leave real stock on a ghost pallet.
INSERT INTO inventory_split_command (
    idempotency_key,
    canonical_command,
    source_pallet_id
)
VALUES ($1, $2, $3)
ON CONFLICT ON CONSTRAINT inventory_split_command_idempotency_key_pkey
DO NOTHING
RETURNING movement_id, new_pallet_id;
