[package]
name = "receiving-purchase-order-update"
version.workspace = true
edition.workspace = true
description = "Receiving purchase order update operation component"
license = "Apache-2.0"

[dependencies]
futures-executor = "0.3"
wamn-receiving-data-access = { workspace = true }
wit-bindgen = { workspace = true }

[lib]
crate-type = ["cdylib"]
test = false
bench = false

[lints]
workspace = true

